In [1]:
import numpy as np

In [3]:
arr = np.array([12,34,56,78,90,23,45,67,89])
arr

array([12, 34, 56, 78, 90, 23, 45, 67, 89])

In [5]:
arr1 = arr.reshape(3,3)
arr1

array([[12, 34, 56],
       [78, 90, 23],
       [45, 67, 89]])

In [7]:
arr1.transpose()

array([[12, 78, 45],
       [34, 90, 67],
       [56, 23, 89]])

In [9]:
arr1.T
#same as transpose

array([[12, 78, 45],
       [34, 90, 67],
       [56, 23, 89]])

In [10]:
array = np.arange(60).reshape(6,5,2)
array

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]],

       [[50, 51],
        [52, 53],
        [54, 55],
        [56, 57],
        [58, 59]]])

In [12]:
a1=array.transpose()
a1
#shape = (2,5,6)

array([[[ 0, 10, 20, 30, 40, 50],
        [ 2, 12, 22, 32, 42, 52],
        [ 4, 14, 24, 34, 44, 54],
        [ 6, 16, 26, 36, 46, 56],
        [ 8, 18, 28, 38, 48, 58]],

       [[ 1, 11, 21, 31, 41, 51],
        [ 3, 13, 23, 33, 43, 53],
        [ 5, 15, 25, 35, 45, 55],
        [ 7, 17, 27, 37, 47, 57],
        [ 9, 19, 29, 39, 49, 59]]])

TypeError: 'tuple' object is not callable