In [1]:
import numpy as np

In [6]:
arr = np.random.randn(12)

In [8]:
arr

array([ 1.34983018, -1.23617287,  1.1848128 , -1.20143614, -0.20399484,
       -0.15966757, -0.70206865, -0.81414063, -0.4098736 , -1.1869802 ,
       -0.36331534,  0.87424382])

In [7]:
np.sqrt(arr)
# nan as negative num 

C:\Users\virma\AppData\Local\Temp\ipykernel_5760\2296558006.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr)


array([1.16182192,        nan, 1.08849106,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan, 0.93501007])

In [9]:
arr2 = np.random.randn(12)
arr2

array([-1.01960399,  0.51697265,  0.30669521,  1.13124008,  0.52321602,
        0.50650218, -0.2956013 , -0.7962406 ,  2.51619513, -0.81570693,
        0.10943621, -0.60836852])

In [11]:
np.add(arr,arr2)

array([ 0.3302262 , -0.71920022,  1.49150801, -0.07019606,  0.31922118,
        0.34683461, -0.99766994, -1.61038124,  2.10632153, -2.00268714,
       -0.25387913,  0.26587531])

In [12]:
np.multiply(arr,arr2)

array([-1.37629224, -0.63906756,  0.36337641, -1.35911272, -0.10673337,
       -0.08087197,  0.2075324 ,  0.64825183, -1.03132195,  0.96822798,
       -0.03975985, -0.53186242])

In [14]:
np.minimum(arr,arr2)
#compares corresponding elemnts and returns min from both

array([-1.01960399, -1.23617287,  0.30669521, -1.20143614, -0.20399484,
       -0.15966757, -0.70206865, -0.81414063, -0.4098736 , -1.1869802 ,
       -0.36331534, -0.60836852])