In [1]:
import numpy as np

In [2]:
ls = [12,345,76,4.5,34.9,64,9.09]

In [3]:
arr = np.array(ls)

In [4]:
arr

array([ 12.  , 345.  ,  76.  ,   4.5 ,  34.9 ,  64.  ,   9.09])

In [5]:
arr[0]

12.0

In [6]:
len(arr)

7

In [7]:
arr.shape

(7,)

In [8]:
arr.reshape(1,7)

array([[ 12.  , 345.  ,  76.  ,   4.5 ,  34.9 ,  64.  ,   9.09]])

In [9]:
arr.reshape(7,1)

array([[ 12.  ],
       [345.  ],
       [ 76.  ],
       [  4.5 ],
       [ 34.9 ],
       [ 64.  ],
       [  9.09]])

In [10]:
arr[2:5]

array([76. ,  4.5, 34.9])

In [11]:
arr[3]= 99
arr

array([ 12.  , 345.  ,  76.  ,  99.  ,  34.9 ,  64.  ,   9.09])

In [12]:
arr_slice = arr[1:5]
arr_slice

array([345. ,  76. ,  99. ,  34.9])

In [13]:
arr_slice[2]= 3
arr_slice

array([345. ,  76. ,   3. ,  34.9])

In [14]:
arr[6]=10
arr

array([ 12. , 345. ,  76. ,   3. ,  34.9,  64. ,  10. ])

In [15]:
arr[3]= 14
arr_slice


array([345. ,  76. ,  14. ,  34.9])

In [17]:
arr2= arr.copy()
arr2

array([ 12. , 345. ,  76. ,  14. ,  34.9,  64. ,  10. ])

In [18]:
arr2[3]=68
arr2

array([ 12. , 345. ,  76. ,  68. ,  34.9,  64. ,  10. ])

In [19]:
arr

array([ 12. , 345. ,  76. ,  14. ,  34.9,  64. ,  10. ])

In [20]:
arr[2]= 39
arr2

array([ 12. , 345. ,  76. ,  68. ,  34.9,  64. ,  10. ])

# Multi Dimensionalb ARRAY

In [22]:
arr = np.arange(90)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89])

In [24]:
arr = arr.reshape(9,10)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [25]:
arr.shape

(9, 10)

In [26]:
arr[1,1]

11

In [27]:
arr[1][1]

11

In [28]:
arr=arr.reshape(9,2,5)
# 9 arrays each of 2x5
arr

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]],

       [[60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]],

       [[70, 71, 72, 73, 74],
        [75, 76, 77, 78, 79]],

       [[80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89]]])

In [29]:
arr[4]
#whole 4th array

array([[40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [32]:
arr[3,1,2]

37

In [33]:
arr[4][0]
#first row of 4th array => a vector

array([40, 41, 42, 43, 44])