In [2]:
import numpy as np


In [3]:
arr = np.random.randn(4,4)
arr

array([[ 0.99563708, -0.91118974, -1.00873139, -0.06591665],
       [ 0.61282597, -0.26696065, -0.33197775, -0.83281364],
       [-1.30498305,  0.23673218,  0.10981675,  1.6592226 ],
       [ 0.94965299, -1.52919779,  0.15865502, -0.32686503]])

In [5]:
arr.sum()

-1.8560931120955155

In [6]:
arr.mean()

-0.11600581950596972

In [7]:
arr.std()
#standard deviation

0.8578730551363524

In [8]:
arr.var()
#variance

0.7359461787289792

In [9]:
np.where(arr<0,0,arr)
# is like while (condition, if condition is met return 0, else return original array value)

# press shift+tab at end of function to know its working

array([[0.99563708, 0.        , 0.        , 0.        ],
       [0.61282597, 0.        , 0.        , 0.        ],
       [0.        , 0.23673218, 0.10981675, 1.6592226 ],
       [0.94965299, 0.        , 0.15865502, 0.        ]])

In [11]:
arr.sort()
arr
# each sub array (rows) sorted individually

array([[-1.00873139, -0.91118974, -0.06591665,  0.99563708],
       [-0.83281364, -0.33197775, -0.26696065,  0.61282597],
       [-1.30498305,  0.10981675,  0.23673218,  1.6592226 ],
       [-1.52919779, -0.32686503,  0.15865502,  0.94965299]])