In [1]:
import numpy as np

In [3]:
a = np.arange(15)

In [4]:
a


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
a = a.reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [7]:
a.ndim

2

In [8]:
a.shape

(3, 5)

In [9]:
a.size

15

In [10]:
a.reshape(15,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14]])

In [11]:
list = [ 9,8,7,6,5,4,3,2,1]
arr = np.array(list)
arr

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [12]:
list_2dim = [ [1,2,3],[4,5,6],[7,8,9]]
arr2 = np.array(list_2dim)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
np.zeros(20).reshape(2,10)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [18]:
np.ones(40).reshape(2,4,5)
# 3 dimensional

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [19]:
np.eye(4)
#identity 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.empty(5)
# numbers very close to 0

array([7.74860419e-304, 7.74860419e-304, 7.74860419e-304, 7.74860419e-304,
       7.74860419e-304])

In [21]:
e = np.empty(4)
e

array([1., 1., 1., 1.])

In [24]:
np.random.random((3,3))

array([[0.54879113, 0.05288868, 0.72125201],
       [0.364229  , 0.37798853, 0.31254939],
       [0.72844389, 0.62398086, 0.65232606]])

# array operations